# Generated by Django 4.2 on 2023-09-24 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('0aac0f62-7ae5-4bcb-976a-0850a7dbdf8d')),
        ),
    ]
