# Generated by Django 4.2 on 2023-09-24 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0002_alter_participants_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('dc42bc77-7051-41dd-8e79-3cf9d08ca392'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('37ba9be1-ea10-4a4a-88eb-79a344a48177')),
        ),
    ]
