# Generated by Django 4.2 on 2023-09-29 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0005_alter_match_match_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournaments',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.organization'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('5f8d7aa2-434a-4d03-95e8-737a0ef6afb8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('c0acfdd1-1d38-41a5-8d32-3033d7d8d31e')),
        ),
    ]
