# Generated by Django 4.2 on 2023-10-02 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0007_rename_participant_one_result_match_participant_one_wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('e74197e5-72f1-450b-98d6-5467c17dfd0d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('c59a6d39-4342-4c28-b7ad-2979e9060baa')),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
