# Generated by Django 4.2 on 2023-10-08 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0010_alter_match_match_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='participant_one_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='participant_two_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('1d4b1d64-90e1-46be-b1d6-8c38c4aca805'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('26cfc154-55bc-40d6-947d-ce62dc010643')),
        ),
    ]
