# Generated by Django 4.2 on 2023-10-10 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0011_match_participant_one_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('1d6dcf3b-f546-4d67-b9f7-4599157e48ae'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('62913ce4-a900-4278-adbd-380ab8f5153d')),
        ),
    ]
