# Generated by Django 4.2 on 2023-10-15 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0013_match_tie_alter_match_match_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='score',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('9387dd2e-3542-4679-9486-10b8d9d97c2b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='rounds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='tournaments_app.rounds'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.UUIDField(default=uuid.UUID('b45cb783-ef3a-4cad-865d-5d698647d524')),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant', to='tournaments_app.participants'),
        ),
    ]
