# Generated by Django 4.2 on 2023-10-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0015_alter_match_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tournaments_app.tournaments'),
        ),
    ]
