# Generated by Django 4.2 on 2023-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0017_tournamentadmin_tournaments_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
