# Generated by Django 4.2 on 2023-10-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0018_tournaments_round_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='round_time_estimate',
            field=models.IntegerField(default=0),
        ),
    ]
