# Generated by Django 4.2 on 2023-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0019_tournaments_round_time_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='round_time_estimate',
            field=models.FloatField(default=0.0),
        ),
    ]
