# Generated by Django 4.2 on 2023-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0021_alter_tournaments_round_time_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='winner',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
