# Generated by Django 4.2 on 2023-10-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0022_tournaments_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='tournament',
        ),
    ]
