# Generated by Django 4.2 on 2023-11-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0024_alter_organizationadmin_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.match')),
            ],
            options={
                'db_table': 'match_conflicts',
            },
        ),
    ]
