# Generated by Django 4.2 on 2023-11-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0025_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments_app.match'),
        ),
    ]
