# Generated by Django 4.2 on 2023-11-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments_app', '0026_alter_conflict_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='omw',
            field=models.FloatField(null=True),
        ),
    ]
